hdfs:
  defaultFS: hdfs://localhost:9000
  partition: 1
  replicas: 1

server:
  port: 8888

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tsquality
    username: qiu
    password: 0924

logging:
  level:
    org.apache.spark: WARN
    org.sparkproject.jetty: WARN
    org.apache.hadoop: WARN

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.edu.tsinghua.tsquality.model.entity

iotdb:
  host: localhost
  port: 6667
  username: root
  password: root
  max-size: 100

pre-aggregation:
#  scan-cron: "0 */10 * * * ?"
  scan-cron: "* * * * * ?"
  executor:
    core-pool-size: 9
    max-pool-size: 15
    queue-capacity: 1000
    name-prefix: pre-aggregation
  data-dir: /Users/tyty/Projects/apache-iotdb-1.1.1-all-bin/data/datanode/data/sequence
  storage:
    type: rdbms
    hdfs:
      compression: none