server:
  port: 8888
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tsquality
    username: qiu
    password: 0924
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.edu.tsinghua.tsquality.model.entity

iotdb:
  host: localhost
  port: 6667
  username: root
  password: root
  max-size: 100

pre-aggregation:
  executor:
    core-pool-size: 9
    max-pool-size: 15
    queue-capacity: 1000
    name-prefix: pre-aggregation
  data-dir: /Users/tyty/Projects/apache-iotdb-1.1.1-all-bin/data/datanode/data/sequence